import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
export default function Home() {
 return (
   <div className={styles.container}>
     <Head>
     <title>éƒ¨ç½²ãƒªãƒ³ã‚¯ç·¨é›†</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
     </Head>
     <header className={styles.header}>
     <h1>ã†ãªãŽã€‚</h1>
     </header>
     <main className={styles.main}>
       <left className={styles.left}>
        <ul className={styles.ul}>
         <li><Link href="/">éƒ¨ç½²ãƒªãƒ³ã‚¯ç·¨é›†</Link></li>
         <li><Link href="/second">å½“ç•ªç™»éŒ²</Link></li>
         <li><Link href="/third">é£Ÿå ‚ãƒ¡ãƒ‹ãƒ¥ãƒ¼</Link></li>
         <li>ã‚«ãƒ†ã‚´ãƒªãƒ¼ç·¨é›†</li>
         <li>éƒ¨ç½²ç®¡ç†</li>
         <li>å›ºå®šãƒªãƒ³ã‚¯ç·¨é›†</li>
         <li>ç¤¾å“¡æƒ…å ±ä½œæˆ</li>
         <li>æ“ä½œè¨˜éŒ²ç¢ºèª</li>
        </ul>
       </left>
      
       <right className={styles.right}>
        <h1>éƒ¨ç½²ãƒªãƒ³ã‚¯ç·¨é›†</h1>
        <div className={styles.text}>
          <ul>
          <li>ãƒªãƒ³ã‚¯å</li>
          <li>ãƒªãƒ³ã‚¯URL</li>
          </ul>
        </div>
        <div className={styles.textbox}>
          <ul>
           <li><input type="text"/><input type="text"/></li>
           <li></li>
         </ul>
        </div>
 
 
       </right>
      
      
     </main>
 
     <footer className={styles.footer}>
      
     </footer>
   </div>
 )
}

